<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>assettotrigger</name>
   <tag></tag>
   <elementGuidId>9dfefce5-d015-4bb2-ab24-2a6e800cc38f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@dx-select-box='${name}']//input[@type='text']</value>
   </webElementProperties>
</WebElementEntity>
