<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>floatcalendar</name>
   <tag></tag>
   <elementGuidId>0801d1b8-0e28-4ff5-ba6e-fc07536ce3eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@dx-date-box='configFloatStartDateBox']//div[@class='dx-dropdowneditor-icon']</value>
   </webElementProperties>
</WebElementEntity>
