<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>recurrance_pattern</name>
   <tag></tag>
   <elementGuidId>64fce1ee-06f4-463e-85d0-1e35f93b5eae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='schedulerControlWrapperRight']//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='schedulerControlWrapperRight']//input[@type='text']</value>
   </webElementProperties>
</WebElementEntity>
