<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enter_value_INV_WKO</name>
   <tag></tag>
   <elementGuidId>fd2ca9e5-7e9d-4c57-9ece-52a2a1cdda80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class=&quot;dx-texteditor-input&quot;])[41]</value>
   </webElementProperties>
</WebElementEntity>
