<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MRR_dropdown_click</name>
   <tag></tag>
   <elementGuidId>bc073b35-c290-43b8-bc92-9dbd2b64cf2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class=&quot;dx-dropdowneditor-icon&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;dx-dropdowneditor-icon&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
