<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_at_INV_clerk</name>
   <tag></tag>
   <elementGuidId>849e913a-e165-4ac2-847a-278c388c7885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@ng-model=&quot;searchAndAddValue&quot;]</value>
   </webElementProperties>
</WebElementEntity>
