<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WKO_open_close_calanderclick</name>
   <tag></tag>
   <elementGuidId>8199a710-6242-4c37-a270-da272ab0ef9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;dx-dropdowneditor-icon&quot;])[12]</value>
   </webElementProperties>
</WebElementEntity>
