<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calenderclick_closepur</name>
   <tag></tag>
   <elementGuidId>c5c2286e-3550-497a-88ba-957b31ba7aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class=&quot;dx-dropdowneditor-icon&quot;])[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;dx-dropdowneditor-icon&quot;])[19]</value>
   </webElementProperties>
</WebElementEntity>
