<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calenderclick_closepur_list</name>
   <tag></tag>
   <elementGuidId>c5f8e5a0-423d-48ab-9b3d-8a8510606e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@role=&quot;button&quot;])[23]</value>
   </webElementProperties>
</WebElementEntity>
