<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>orderdate_click</name>
   <tag></tag>
   <elementGuidId>f9550d8d-3506-4d21-b5a6-0c840a1c1070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;OrderDate&quot;]//div[@role=&quot;button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
