<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>orginator_edit</name>
   <tag></tag>
   <elementGuidId>5fc24af8-8b56-4b8a-ad64-6036148b25dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class=&quot;dx-texteditor-container&quot;]//input[@role=&quot;textbox&quot;])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;dx-texteditor-container&quot;]//input[@role=&quot;textbox&quot;])[3]</value>
   </webElementProperties>
</WebElementEntity>
