<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Originator_change</name>
   <tag></tag>
   <elementGuidId>d01bb4e3-72f4-486b-b61b-3c38d5e0e342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;Originator&quot;]//input[@maxlength='100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;Originator&quot;]//input[@maxlength='100']</value>
   </webElementProperties>
</WebElementEntity>
