<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textobj</name>
   <tag></tag>
   <elementGuidId>e367fd1b-9a62-46a2-b6d6-5d9dbe0eb91a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;${name}&quot;]//input[@tabindex=&quot;0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;${name}&quot;]//input[@tabindex=&quot;0&quot;]</value>
   </webElementProperties>
</WebElementEntity>
