<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>specific_asset_drop</name>
   <tag></tag>
   <elementGuidId>dd1437a8-fa13-4cff-a065-df4c6669de2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@fieldname='${name}']//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@fieldname='${name}']//input[@type='text']</value>
   </webElementProperties>
</WebElementEntity>
