<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calendar_tom</name>
   <tag></tag>
   <elementGuidId>62282e0c-42ab-4fef-9e4b-872aa1cb8050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='dx-calendar-body']//td[@data-value='${date}'])[${value}]</value>
   </webElementProperties>
</WebElementEntity>
