<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_wo</name>
   <tag></tag>
   <elementGuidId>4528719f-ca81-4851-942b-228e93399f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//td[@role=&quot;gridcell&quot;]//input[@class='dx-texteditor-input'])[3]</value>
   </webElementProperties>
</WebElementEntity>
