<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hideListLayout</name>
   <tag></tag>
   <elementGuidId>711cd6ca-53e0-4a1d-b25e-be80b119f8c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='Minimize']/following-sibling::div[@id='sb-collapse']</value>
   </webElementProperties>
</WebElementEntity>
