<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HoldReason</name>
   <tag></tag>
   <elementGuidId>185436af-a85a-4be5-b291-35453349175d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'ViewHoldReasonCaption')]/following::div[@id='${name}']//input[@role='combobox']</value>
   </webElementProperties>
</WebElementEntity>
