<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>holduntil_calendar</name>
   <tag></tag>
   <elementGuidId>388f5b0c-8866-460d-9513-4f76d4e1cdb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'ViewHoldReasonCaption')]/following::div[@id='HoldUntil']//div[@class='dx-dropdowneditor-icon']</value>
   </webElementProperties>
</WebElementEntity>
