<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>infoLink_Search</name>
   <tag></tag>
   <elementGuidId>b103019e-b72e-435f-9431-ca9d12f36bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'${name}')]/following::input[@maxlength='50']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'${name}')]/following::input[@maxlength='50']</value>
   </webElementProperties>
</WebElementEntity>
