<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>layoutlist</name>
   <tag></tag>
   <elementGuidId>5b0fec90-7788-4cb3-898b-138c4f725fba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@dx-select-box=&quot;listviewselectbox&quot;]//div[@role='button']</value>
   </webElementProperties>
</WebElementEntity>
