<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Close_Yes</name>
   <tag></tag>
   <elementGuidId>9150eda8-ea43-4f3d-87a7-33e77ba15472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;dx-button-content&quot;]/span[contains(text(),'Yes')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;dx-button-content&quot;]/span[contains(text(),'Yes')]</value>
   </webElementProperties>
</WebElementEntity>
