<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save_ListLayout</name>
   <tag></tag>
   <elementGuidId>c5753b6c-1278-45cf-b351-b74e27f2a786</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@ng-click='saveWorkOrderFromListview()']//a[contains(@title,'Save')]</value>
   </webElementProperties>
</WebElementEntity>
