<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wo_fromlist</name>
   <tag></tag>
   <elementGuidId>3edfadb8-f5b2-45c2-81b9-5858abc85aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//td[@role=&quot;gridcell&quot;]/div[contains(@title,'WKO')])[${value}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//td[@role=&quot;gridcell&quot;]/div[contains(@title,'WKO')])[${value}]</value>
   </webElementProperties>
</WebElementEntity>
