<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WORecords</name>
   <tag></tag>
   <elementGuidId>e9ca58c6-83e1-4d0c-9da2-b88a53008d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class='ng-scope']/a[@title='${name}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@class='ng-scope']/a[@title='${name}']</value>
   </webElementProperties>
</WebElementEntity>
