<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>report_radio</name>
   <tag></tag>
   <elementGuidId>dd3c9ed2-bff7-4e98-a005-1832791e2fef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span/input[@value='${value}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span/input[@value='${value}']</value>
   </webElementProperties>
</WebElementEntity>
